spring:
  datasource:
      url: jdbc:mysql://114.242.34.137:33306/microsands_dev?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
